# Deploy the exact kernels accepted for this release, independently of the
# import library used to link the application. Never fall back to a stock DLL.
if(CMAKE_VERSION VERSION_LESS 3.19)
  message(FATAL_ERROR "Verified Windows mpv deployment requires CMake 3.19 or newer")
endif()
if(NOT IS_DIRECTORY "${MPV_RUNTIME_DIR}")
  message(FATAL_ERROR "Set TIGEREST_MPV_RUNTIME_DIR to the verified RIFE mpv runtime directory")
endif()
file(READ "${MPV_LOCK_FILE}" mpv_lock)
string(JSON mpv_schema GET "${mpv_lock}" schemaVersion)
if(NOT mpv_schema EQUAL 1)
  message(FATAL_ERROR "Unsupported mpv runtime lock")
endif()
foreach(role primary fallback)
  if(role STREQUAL "primary")
    set(dll_name libmpv-2.dll)
  else()
    set(dll_name libmpv-fallback.dll)
  endif()
  string(JSON expected_hash GET "${mpv_lock}" ${role} sha256)
  string(JSON expected_size GET "${mpv_lock}" ${role} size)
  set(dll_path "${MPV_RUNTIME_DIR}/${dll_name}")
  if(NOT EXISTS "${dll_path}" OR IS_SYMLINK "${dll_path}")
    message(FATAL_ERROR "Verified mpv ${role} DLL is missing: ${dll_name}")
  endif()
  file(SHA256 "${dll_path}" actual_hash)
  file(SIZE "${dll_path}" actual_size)
  if(NOT actual_hash STREQUAL expected_hash OR NOT actual_size EQUAL expected_size)
    message(FATAL_ERROR "Verified mpv ${role} DLL checksum/size mismatch")
  endif()
endforeach()
# Verify both before writing either into the bundle. file(INSTALL) can skip a
# stale destination with the same timestamp, so copy and verify actual bytes.
file(MAKE_DIRECTORY "${MPV_INSTALL_DIR}/licenses/mpv-rife")
foreach(role primary fallback)
  if(role STREQUAL "primary")
    set(dll_name libmpv-2.dll)
  else()
    set(dll_name libmpv-fallback.dll)
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${MPV_RUNTIME_DIR}/${dll_name}"
                          "${MPV_INSTALL_DIR}/${dll_name}" RESULT_VARIABLE copy_result)
  if(NOT copy_result EQUAL 0)
    message(FATAL_ERROR "Failed to deploy verified mpv ${role} DLL")
  endif()
  string(JSON expected_hash GET "${mpv_lock}" ${role} sha256)
  string(JSON expected_size GET "${mpv_lock}" ${role} size)
  file(SHA256 "${MPV_INSTALL_DIR}/${dll_name}" deployed_hash)
  file(SIZE "${MPV_INSTALL_DIR}/${dll_name}" deployed_size)
  if(NOT deployed_hash STREQUAL expected_hash OR NOT deployed_size EQUAL expected_size)
    message(FATAL_ERROR "Deployed mpv ${role} DLL checksum/size mismatch")
  endif()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${MPV_LOCK_FILE}"
                        "${MPV_INSTALL_DIR}/licenses/mpv-rife/mpv-runtime-lock.json"
                RESULT_VARIABLE copy_result)
if(NOT copy_result EQUAL 0)
  message(FATAL_ERROR "Failed to deploy mpv runtime lock")
endif()
