# Shared configure/install preflight. A missing path must never turn the
# compositor synchronization fix into an optional packaging feature.
function(tigerest_validate_webengine runtime qt_version source_root)
  if(NOT IS_DIRECTORY "${runtime}")
    message(FATAL_ERROR "Set TIGEREST_WEBENGINE_RUNTIME to the verified patched QtWebEngine runtime directory (see dev/windows/qtwebengine/README.md)")
  endif()
  if(NOT EXISTS "${runtime}/tigerest-webengine.json")
    message(FATAL_ERROR "Patched WebEngine build manifest is missing")
  endif()
  file(READ "${runtime}/tigerest-webengine.json" runtime_manifest)
  string(JSON runtime_version GET "${runtime_manifest}" qtVersion)
  string(JSON expected_patch_hash GET "${runtime_manifest}" patchSha256)
  string(JSON expected_core_hash GET "${runtime_manifest}" coreSha256)
  if(NOT runtime_version STREQUAL "${qt_version}")
    message(FATAL_ERROR "WebEngine runtime ${runtime_version} does not match Qt ${qt_version}")
  endif()
  foreach(name Qt6WebEngineCore.dll Qt6WebEngineQuick.dll
               Qt6WebEngineQuickDelegatesQml.dll QtWebEngineProcess.exe)
    if(NOT EXISTS "${runtime}/bin/${name}")
      message(FATAL_ERROR "Incomplete patched WebEngine runtime: ${name}")
    endif()
  endforeach()
  foreach(dir resources translations qml)
    if(NOT IS_DIRECTORY "${runtime}/${dir}")
      message(FATAL_ERROR "Incomplete patched WebEngine runtime: ${dir}")
    endif()
  endforeach()
  file(SHA256 "${source_root}/dev/windows/qtwebengine/qtwebengine-6.9.3-d3d11-producer-sync.patch" patch_hash)
  file(SHA256 "${runtime}/bin/Qt6WebEngineCore.dll" core_hash)
  string(TOLOWER "${expected_patch_hash}" expected_patch_hash)
  string(TOLOWER "${expected_core_hash}" expected_core_hash)
  if(NOT patch_hash STREQUAL expected_patch_hash OR NOT core_hash STREQUAL expected_core_hash)
    message(FATAL_ERROR "Patched WebEngine DLL or source patch does not match its build manifest")
  endif()
  set(TIGEREST_WEBENGINE_CORE_SHA256 "${core_hash}" PARENT_SCOPE)
endfunction()
