const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../native/nativeshell.js'),'utf8');
const start=source.indexOf('function installWindowModeEntry()'),end=source.indexOf('\ninstallMpvSettingsEntry();',start);
assert.ok(start>=0&&end>start);
let observer,mutations=0,button,fullscreen=false,change;
const document={head:{appendChild(){}},documentElement:{},getElementById:id=>id==='tigerest-window-mode-button'?button:id==='tigerest-window-mode-style'?{}:null,querySelector:()=>({parentElement:{insertBefore:b=>{button=b;}}}),createElement:()=>({addEventListener(){},setAttribute(){},get textContent(){return this.value||'';},set textContent(value){this.value=value;mutations++;}})};
const window={initCompleted:Promise.resolve(),api:{window:{isFullScreen:async()=>fullscreen,fullScreenSwitched:{connect:fn=>{change=fn;}}}}};
vm.runInNewContext(source.slice(start,end)+'\ninstallWindowModeEntry();',{document,window,MutationObserver:class{constructor(fn){observer=fn;}observe(){}},console});
(async()=>{
 await new Promise(r=>setImmediate(r));
 const before=mutations;observer();observer();
 assert.equal(mutations,before,'unchanged button must not create child-list mutations in its own observer');
 fullscreen=true;await change();assert.equal(button.textContent,'窗口');
 button=undefined;observer=undefined;window.tigerestAndroidApi={};
 vm.runInNewContext(source.slice(start,end)+'\ninstallWindowModeEntry();',{document,window,MutationObserver:class{constructor(fn){observer=fn;}observe(){}},console});
 await new Promise(r=>setImmediate(r));
 assert.equal(button,undefined,'Android must not mount a desktop window-mode control');
 assert.equal(observer,undefined,'Android should not watch the DOM for a desktop-only control');
 console.log('window button: observer terminates and fullscreen label updates');
})().catch(e=>{console.error(e);process.exitCode=1;});
