const assert=require('node:assert/strict');const {run,delay}=require('./cdp.cjs');
require('./media_fixture.cjs')(async({c,url,wait,tap,shot,requests})=>{
 const show=async()=>{const d=await c.evaluate('api.system.debugInformation()');if(!d.controlsVisible){run('shell','input','tap',String(Math.round((d.pane.left+d.pane.right)/2)),String(Math.round((d.pane.top+d.pane.bottom)/2)));await wait('api.system.debugInformation().then(d=>d.controlsVisible)');}};
 await c.evaluate(`(()=>{window.playerEvents=[];const events={trigger:(sender,name,args=[])=>playerEvents.push({kind:sender.id,name,args})};window.audio=new _mpvAudioPlayer({events,appSettings:{get:()=>1,set(){}},appHost:{},toast:()=>{}});return audio.play({url:'${url}/media.mp4',item:{Id:'audio-fixture',Name:'音乐测试'},playerStartPositionTicks:50000000});})()`);
 await wait('audio.currentTime()>5500');let audioInfo=await c.evaluate('api.player.mpvDiagnostics()');assert.equal(audioInfo.audioTrack,1);assert.equal(audioInfo.subtitleTrack,-1);assert.equal(await c.evaluate('api.system.debugInformation().then(v=>v.videoVisible)'),false);
 await c.evaluate('api.player.stop()');await delay(200);assert.equal(await c.evaluate('playerEvents.filter(e=>e.kind==="mpvaudioplayer"&&e.name==="stopped").length'),1);assert.equal(await c.evaluate('audio.currentSrc()'),null);assert.equal(await c.evaluate('playerEvents.find(e=>e.name==="stopped").args[0].playNext'),false);await c.evaluate('audio.destroy()');
 await c.evaluate(`(()=>{window.videoPlayer=new _mpvVideoPlayer({events:{trigger:(s,n,a=[])=>playerEvents.push({kind:s.id,name:n,args:a})},loading:{hide(){},show(){}},appSettings:{get:()=>1,set(){}},appHost:{},appRouter:{},globalize:{translate:x=>x},confirm:()=>Promise.resolve(),dashboard:{default:{setBackdropTransparency(){}}}});return videoPlayer.play({url:'${url}/media.mp4',item:{Id:'video-fixture',Name:'外置字幕验收'},fullscreen:false,mediaSource:{DefaultAudioStreamIndex:1,DefaultSubtitleStreamIndex:-1,MediaStreams:[{Type:'Video',Index:0},{Type:'Audio',Index:1},{Type:'Audio',Index:2},{Type:'Subtitle',Index:3,DisplayTitle:'外置字幕一',IsExternal:true,DeliveryMethod:'External',DeliveryUrl:'/one.srt'},{Type:'Subtitle',Index:4,DisplayTitle:'外置字幕二',IsExternal:true,DeliveryMethod:'External',DeliveryUrl:'/two.srt'}]}});})()`);
 await wait('videoPlayer.currentTime()>1000');assert.equal((await c.evaluate('api.player.getSubtitleStreams()')).length,2);
 await c.evaluate('api.player.pause()');await delay(500);
 // Recover the controls by tapping the center, then use the actual native menus.
 await show();await tap('更多');await tap('字幕');await tap('外置字幕二');await wait('api.player.mpvDiagnostics().then(d=>d.subtitleTrack>0)');assert.ok(requests.includes('/two.srt'));assert.ok(!requests.includes('/one.srt'));
 await show();await tap('更多');await tap('字幕');await tap('外置字幕一');await wait('api.player.mpvDiagnostics().then(d=>d.tracks.some(t=>t["external-filename"]?.endsWith("one.srt")))');assert.ok(requests.includes('/one.srt'));
 await show();await tap('更多');await tap('字幕偏移');await tap('0.0');run('shell','input','keycombination','113','29');run('shell','input','text','1.5');await tap('保存');assert.equal((await c.evaluate('api.player.mpvDiagnostics()')).subtitleDelay,1.5);
 await c.evaluate('api.player.play()');await delay(4200);assert.equal(await c.evaluate('api.system.debugInformation().then(d=>d.controlsVisible)'),false);shot('external-subtitles-controls-hidden');
 await show();
 const before=await c.evaluate('api.player.getPosition()');await assert.rejects(c.evaluate(`api.player.queueMedia('${url}/media.mp4',{}, {})`),/Emby/);assert.ok(await c.evaluate('api.player.getPosition()')>=before);
 await c.evaluate('videoPlayer.stop(true)');await delay(200);assert.equal(await c.evaluate('playerEvents.filter(e=>e.kind==="mpvvideoplayer"&&e.name==="stopped").length'),1);
 console.log(JSON.stringify({passed:true,sharedMusic:audioInfo,subtitleRequests:requests.filter(r=>r.endsWith('.srt')),stoppedReports:await c.evaluate('playerEvents.filter(e=>e.name==="stopped")')}));
},(req,res)=>{if(!req.url.endsWith('.srt'))return false;res.setHeader('Content-Type','application/x-subrip');res.end('1\n00:00:00,000 --> 00:01:30,000\n'+(req.url==='/one.srt'?'字幕一':'字幕二')+'\n');return true;}).catch(e=>{console.error(e);process.exitCode=1;});
